### ISSUE TITLE
How to Use Gopay payment channel?

### ISSUE THREAD

**Issue by bjkuncoro** [adityahas/react-native-midtrans-payment#1]
i found this repo, i want to use it for gopay payment, can u help me please, terima kasih

**Comment by adityahas** [comment]
Hi,
Of course, what can I help?

**Comment by adityahas** [comment]
Closed due to inactivity

**Comment by akanksha-chaudhary** [comment]
I want to integrate gopay with my react-native application. Please let me know if anyone can help me regarding this.
