### ISSUE TITLE
_regenerator.default.async is not a function

### ISSUE THREAD

**Issue by ramadhanoo** [adityahas/react-native-midtrans-payment#2]
<img width="429" alt="Screen Shot 2020-01-17 at 13 18 25" src="https://user-images.githubusercontent.com/32843793/72588758-dd748780-392b-11ea-9687-147f81893f1a.png">

bagaimana mas cara mengatasi nya? kalau saya hilangkan async nya akan muncul seperti ini

<img width="429" alt="Screen Shot 2020-01-17 at 13 21 30" src="https://user-images.githubusercontent.com/32843793/72588900-4d830d80-392c-11ea-986c-213bb23e845a.png">

saya menggunakan react-native versi "0.59.8"
code saya: 

render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity style={{ backgroundColor: 'red', height: 100, weight: 200 }} onPress={() => this.pay() }>
          <Text style={styles.welcome} >Welcome to React Native!</Text>
        </TouchableOpacity>
        
      </View>
    );
  }

**Comment by adityahas** [comment]
Async disini maksudnya yang di async pay() kan?

Harusnya tidak masalah as long callback nya di handle.
Untuk screenshot kedua kayaknya itu karena param yang diinput ke PaymentGateway.checkOut ada yang tidak valid.

**Comment by ramadhanoo** [comment]
pay() {

        const optionConnect = {
            clientKey: "SB-Mid-client-Ellc274P6h6HEUC6",
            urlMerchant: "https://domain.net", // will hit https://domain.net/charge
            sandbox : true, // works on iOS only, change it to false on production
        }

        const transRequest = {
            transactionId: "0231",
            totalAmount: 4000
        }

        const itemDetails = [
            {id: "001", price: 1000, qty: 4, name: "peanuts"}
        ];

        const creditCardOptions = {
            saveCard: false,
            saveToken: false,
            paymentMode: "Normal",
            secure: false
        };

        const userDetail = {
            fullName: "jhon",
            email: "jhon@payment.com",
            phoneNumber: "0850000000",
            userId: "U01",
            address: "street coffee",
            city: "yogyakarta",
            country: "IDN",
            zipCode: "59382"
        };

        const optionColorTheme = {
            primary: '#c51f1f',
            primaryDark: '#1a4794',
            secondary: '#1fce38'
        }

        const optionFont = {
            defaultText: "open_sans_regular.ttf",
            semiBoldText: "open_sans_semibold.ttf",
            boldText: "open_sans_bold.ttf"
        }

        const callback = (res) => {
            console.log(res)
        };

        PaymentGateway.checkOut(
            optionConnect,
            transRequest,
            itemDetails,
            creditCardOptions,
            userDetail,
            optionColorTheme,
            optionFont,
            callback
        );
    }

bisa tolong koreksi kak soalnya saya ngambil sama persis dari contoh

**Comment by adityahas** [comment]
`clientKey` ini bisa di liat di Midtrans akun kamu.
`urlMerchant` ini harus di set up di backend kamu sendiri juga

Mungkin bisa dibaca dulu dokumentasi dari Midtrans ya.

**Comment by ramadhanoo** [comment]
bisa minta code backend nya mas buat referensi?

**Comment by adityahas** [comment]
Di github sudah ada yang bikin, monggo di googling saja :)

**Comment by adityahas** [comment]
Closed for now due to irrelevant issue
