### ISSUE TITLE
[ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by farahnahwa** [adityahas/react-native-midtrans-payment#3]
request.post({
    url: url,
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      'Authorization': "Basic " + base64.encode("SB-Mid-server-w5e5xXjxtHL7ecHJ48qcnEhT:")
    },
    body: JSON.stringify(reqBody)
  }, function(err, response, body) {
    if(err) {
      console.log(err);
      console.log("error")
    } else {
      var respObj = parseJson(body);
    console.log(respObj);
    res.json(respObj);
    res.status(200).send(reqBody)
    }
    
  });

maaf kak ini kode backend saya padahal response nya sudah success tapi dari client nya unsuccessful / tidak menuju ke payment nya

<img width="429" alt="Screen Shot 2020-02-01 at 01 21 19" src="https://user-images.githubusercontent.com/60520590/73563957-2a5e6f00-4491-11ea-8cef-f244dbe2ef67.png">

**Comment by adityahas** [comment]
Boleh liat log di android nya?
Btw, error message [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client, itu AFAIK error disisi backend, betul?

**Comment by myrsapp** [comment]
Same here!
ios udah bisa, yang android sama error nya seperti di atas.

**Comment by TerraRome** [comment]
saya juga sama nih transaction unsuccessfull ada saran gak itu masalahnya dimana @adityahas

**Comment by adityahas** [comment]
Hi guys, ada yang bisa share log dari sisi android maupun BE kah? Impossible untuk solve issue ini tanpa adanya clue. @myrsapp @TerraRome

**Comment by adityahas** [comment]
@farahnahwa AFAIK `ERR_HTTP_HEADERS_SENT` itu terjadi karena send response 2x, yaitu 
```
res.json(respObj);
res.status(200).send(reqBody)
```
