### ISSUE TITLE
Custom merchant checkout endpoint

### ISSUE THREAD

**Issue by webowodev** [adityahas/react-native-midtrans-payment#5]
Hi mas, thanks untuk librarynya.
Mau nanya nih, dibagian `optionConnect.urlMerchant` as default kan bakal nembak `/charge` ketika melakukan checkout, nah kalo di backend merchant yang ku buat endpoint nya mengarah ke `checkout` kira2 bagaimana implementasi untuk custom endpointnya ? Thankyou.

Big salute for your work!

**Comment by adityahas** [comment]
Halo mas, 

Seinget saya url `/charge` itu di hardcode/define disisi Midtrans SDK nya, jadi gak bisa dicustom. Kurang tau untuk saat ini, apakah sudah support custom url atau belum.

Thanks,
